### ISSUE TITLE
Cannot start on Debian Stable (Linux)

### ISSUE THREAD

**Issue by Liokardo** [hrehfeld/QuakeInjector#138]
Debian 10.10

```
~/Downloads/quakeinjector-alpha04 $ java -jar quakeinjector.jar
Error: LinkageError occurred while loading main class de.haukerehfeld.quakeinjector.QuakeInjector
	java.lang.UnsupportedClassVersionError: de/haukerehfeld/quakeinjector/QuakeInjector has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Java packages i have installed (javascript packages removed):
```
~/Downloads/quakeinjector-alpha04 $ apt list --installed "*java*"
Listing... Done
ca-certificates-java/stable,stable,now 20190405 all [installed,automatic]
java-common/stable,stable,now 0.71 all [installed,automatic]
java-package/stable,stable,now 0.62 all [installed]
libatk-wrapper-java-jni/stable,now 0.33.3-22 amd64 [installed,automatic]
libatk-wrapper-java/stable,stable,now 0.33.3-22 all [installed,automatic]
```

Openjdk packages:
```
~/Downloads/quakeinjector-alpha04 $ apt list --installed "*openjdk*"
Listing... Done
openjdk-11-jre-headless/stable,stable,now 11.0.11+9-1~deb10u1 amd64 [installed,automatic]
openjdk-11-jre/stable,stable,now 11.0.11+9-1~deb10u1 amd64 [installed,automatic]
```

**Comment by WRFitch** [comment]
Hi Liokardo, I believe you're going to need at least OpenJDK version 15 to use alpha04. If that doesn't work, I'll give this a look this week. 

In the meantime, @SpiritQuaddicted it may be worth updating the installation instructions to be more specific since [the link](https://adoptopenjdk.net/) looks like it recommends OpenJDK 11. Since this appears to be a common problem, it may also be worth compiling future releases with the latest LTS version.

**Comment by SpiritQuaddicted** [comment]
Argh :(
It would be great if someone checked if we *really* need OpenJDK 15 or if it works with 11. I just build the jar with what was on my system and thought it would be ok.

**Comment by WRFitch** [comment]
I'm getting the same problem running OpenJDK 11 on my Ubuntu machine. The next LTS java version most people will have is 17, due to release in September, so you _could_ leave this until then and most people's standard install will deal with it, but releasing a v4.1 compiled with version 11 is probably better in the meantime.

**Comment by SpiritQuaddicted** [comment]
https://github.com/hrehfeld/QuakeInjector/releases/tag/alpha04-gradle should work with Java 8 and newer.
