### ISSUE TITLE
How to Get QI Alpha06 Running in Windows 10? Do I need Java?

### ISSUE THREAD

**Issue by televators** [hrehfeld/QuakeInjector#150]
For the past bit, Quake Injector couldn't fetch the mod DB. I see that there was a recent fix due to bad certs or something.
I downloaded the new alpha06 release and put it exactly where alpha05 has been for over a year. I cannot get QI to run. To clarify, I unzipped and overwrote the previous lib and runtime directories as well as the executable. There are no permission issues that I can see.

The docs currently say that I should be able to just download Quake Injector, run it, and bada bing. When I run it, I get an error saying it couldn't create the Java Virtual Machine. I completely uninstalled Java and then tried installing fresh. Still doesn't work. Have cleared my system PATH, have readded Java to PATH, have restarted, have tried running QI as Administrator, checked for permission issues, I'm stumped.

I've never been able to get straight what Java "thing" I'm supposed to have installed. According to the QI docs, I shouldn't have to have Java installed at all. Can someone enlighten me on how I'm supposed to run Quake Injector Alpha06 on Windows 10 now? The docs just say, "Download and run!" and it seems like it's not actually that simple.

QuakeInjector Alpha05 was working just fine for the past year and nothing on my system has changed. QI just stopped working, and the latest version just doesn't work either. Not having issues with any other program, just QI (and maybe Java?).

Appreciate any kind of tip or direction.

**Comment by hrehfeld** [comment]
We will definately need the exact error message. :-)

21 Apr 2024 04:11:49 Justin Higgs ***@***.***>:

**Comment by SpiritQuaddicted** [comment]
> To clarify, I unzipped and overwrote the previous lib and runtime directories as well as the executable.

According to https://discuss.quaddicted.com/t/quake-injector-alpha06-fixed-server-connection-issues/7489/4 you need to remove the previous installation otherwise there is a mixture of different versions of Java things or something.

Make sure you keep your database of installed content though, some .xml file, I don't know the filename right now.

If that does not fix it, please re-open this issue with more information (i.e. what gets printed when you try to launch the exe in a command shell).
